### ISSUE TITLE
No updates, is this abandoned?

### ISSUE THREAD

**Issue by dcforeman** [LeeBamberTGC/Dark-Basic-Pro#3]
Hi been about a month since the last update. The IDE is still broken, shadows don't work on platforms 8.1 and 10 and it gives game guru error messages instead of dbpro error messages.

Is this project not being managed and updated anymore? Is it dead?

**Comment by Traductus** [comment]
Hi dcforeman,

**IDE**

My best guess is that the uploaded binary will remain for now as it is unless Lee decides otherwise. 

The reason is that the IDE cannot be fixed directly from the source code in the repository because it requires a commercial component to complete its compilation. At this moment, as far as I know, only Lee has access to the component in the version required by the solution.

As Lee already said, the source code can be amended to use the latest version of the component. The component is available at http://www.bcgsoft.com/bcgcontrolbarpro.htm.

The project hasn't been abandoned. Lee has already done his part by very generously making DBP an open source project and spontaneously uploading a binary version later on. Now it's up to the community to keep DBP alive, healthy and running in its new ecosystem. In that regard, there is an undergoing effort to replace the IDE with a full open source alternative. However, there are no dead lines set or a scheduled release for it.

**Shadows**
1. Could you please elaborate on what's wrong with the shadow commands? A snippet could be very helpful.
2. What are the exact specifications of the computers? Please include the specific edition of the OS being used (e.g. Windows 10 Home, Pro or Education).

**Error Messages**

I will let @LeeBamberTGC answer this one.

**Comment by TheGameCreators** [comment]
LEE: Alas I'm several years out of circulation with this source code.  I recommend writing your own shaders and shadow techniques so you can understand and debug any shadow code you might need fully. I did this with GameGuru using a modified shadow mapping technique and it worked quite well with just shaders and a few camera image commands :)

LEE: The GameGuru references are due to the latest code I could find to make open source, and there was some crossover but you can simply change the text to put it back as DBP :)
