### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by ghg2** [LeeBamberTGC/Dark-Basic-Pro#7]
[Dark AI - 040906.zip](https://github.com/LeeBamberTGC/Dark-Basic-Pro/files/835358/Dark.AI.-.040906.zip)

to fix it go to the editor folder and open Synergy Editor.cfg (open it with notepad) and look for DBPLocation there you will see 
that the file path is F:\TGCSHARED\Dark-Basic-Pro\Install\ change the F:\ to c:\ and put the files in the folders named (in other words in c:\ make a folder called TGCSHARED and in it make another folder called Dark-Basic-Pro paste the install folder into that) and it will find the Compiler. after that it will work fine, to install the plugins run there install and when it gets to the part called choose destination hit browse and install in to your install folder . C:\TGCSHARED\Dark-Basic-Pro\Install\

**Comment by Traductus** [comment]
Thank you for the contribution. However, I think it'd be better to have the file amended instead of having a lonely how-to-install note in here.

A quick clarification. It seems unnecessary to create a new directory to fit a configurable field/property when you can just point the field/property to the folder where the actual installation sits on. Have you tried this?

Let's say DBP is installed on **%DRIVE%:\%PROGRAM FILES%\dark-basic-pro**. Then the field/property **DBPLocation** in the **Synergy Editor.cfg** file should have that value. Please tell me if it works for you so I can amend the file accordingly. I'd really appreciate your help on this.

I'm also going to set the field/property **LastProject** to an empty string and put a note on how to install the plug-ins on the README file.

**Comment by ghg2** [comment]
the way i say to install it works if you try any other path it wont work. i tryed it and i dont know why but if you just put it in the path thats there and change the f:\ to a C:\ it works fine

**Comment by ghg2** [comment]
yes it works the file path in synergy editor.cfg just has to be the same as the install folder

**Comment by Traductus** [comment]
Thank you very much, ghg2.
I already applied the changes to the source code.
